stages:
  - 🏗️build
  - 🧪tests
  - 📦push
  - 🚀deploy

include:
  - project: 'iut_inf63/generic-ci' # Reference to the gitlab project containing the generic ci scripts
    ref: 'main' # Reference to the gitlab ci generic project branch
    file:
      - 'build/.docker-build.yml' # Name of the file to include

  - component: $CI_SERVER_FQDN/iut_inf63/generic-ci/deploy-portfolio@main
    inputs:
      container_image_path: codefirst.iut.uca.fr/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:main
      namespace_name: $KUBE_PORTFOLIO_NAMESPACE
      kube_portfolio_token: $KUBE_PORTFOLIO_TOKEN

tests-sonar:
  stage: 🧪tests
  image: codefirst.iut.uca.fr/iut_inf63/base-cicd/java21-slim:main
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - echo "🔍 Lancement analyse SonarQube"
    - sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.host.url="$SONAR_HOST" -Dsonar.login="$SONAR_TOKEN" -Dsonar.projectKey="$CI_PROJECT_NAMESPACE:$CI_PROJECT_NAME" -Dsonar.projectName="$CI_PROJECT_NAME" -Dsonar.projectVersion="$CI_COMMIT_SHORT_SHA" -Dsonar.sources=. -Dsonar.sourceEncoding=UTF-8
    - echo "✅ Analyse terminee"
  allow_failure: true

push-image:
  extends: .build-and-push-docker-image
  stage: 📦push
  variables:
    DOCKERFILE_RELATIVE_PATH: docker/Dockerfile
    DOCKERFILE_CONTEXT_PATH: .
    DESTINATION_REGISTRY_IMAGE_NAME: codefirst.iut.uca.fr/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    DESTINATION_REGISTRY_IMAGE_VERSION: main
  allow_failure: true
  when: on_success
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"